# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.6
install: pip install -r requirements/dev.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/main/app.py"
  - export FLASK_DEBUG=1

script: pytest --verbose